spa/spa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import password_reset_confirm, password_reset_complete, password_reset_done
from spaapp.views import ResetPasswordRequestView
#from spa.spaapp import urls as surls

urlpatterns = [
    url(r'^spadmin/', include(admin.site.urls)),
    url(r'', include('spaapp.urls')),
    url(r'', include('administracionAPP.urls')),
    url(r'', include('ubicacionApp.urls')),
    url(r'', include('proveedorApp.urls')),
    url(r'', include('estadisticasApp.urls')),
    url(r'', include('valoracionApp.urls')),


    url(r'^account/reset_password', ResetPasswordRequestView.as_view(), name="password_reset"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
           {'template_name': 'reset_password/password_reset_confirm.html'},
           name='password_reset_confirm'
       ),
    url(r'^reset/password_reset_done', password_reset_done,
           {'template_name': 'reset_password/password_reset_done.html'},
           name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
           {'template_name': 'reset_password/password_reset_confirm.html'},
           name='password_reset_confirm'
           ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'reset_password/password_reset_complete.html'},
           name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spa/administracionAPP/models.py
from django.db import models

# Create your models here.
class Contacto(models.Model):
    nombre_propietario = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    ciudad = models.CharField(max_length=50)
    nombre_empresa = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50)
    tipo_negocio = models.CharField(max_length=50)
    telefono = models.CharField(max_length=10, null=True, blank=True)
    correo = models.EmailField(null=True)
    

spa/templates/home/actividadCreate.html
<!doctype html>
{% extends 'home/base.html' %} {% load staticfiles %} {% block content %} {% block title %}
<title>Create</title>{%endblock title%}

<link href="{% static 'home/css/restaurantes.css' %}" rel="stylesheet" />
<br><br><br><br>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>

<div class="container" >
    <h2>Crear Actividad</h2>
<form action="#" method="POST">{% csrf_token %}
    {% for hidden in formulario.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    <label for="tipo_actividad"><small>* TIPO ACTIVIDAD</small></label><input type="text" name="tipo_actividad" value=""><br>
    <label for="detalles"><small>* DETALLES</small></label><input type="text" name="detalles" value=""><br>
    <input type="submit" value="submit">

</form>
    </div>
{% endblock content %}
</body>
</html>

spa/templates/home/clienteRead.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>CRUD CLIENTE</h2>
<a  href="clienteCreate">Crear Cliente</a>
<table border="1">

    <caption>Registro de Cliente</caption>
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">FECHA INICIO SUSCRIPCION</th>
        <th scope="col">SUSCRIPCION ACTIVA</th>
        <th scope="col">FECHA PAGO</th>
        <th scope="col">DETALLES ADICIONALES</th>
        <th scope="col">PEDIDOS ACTIVOS</th>
        <th scope="col">VALOR SUSCRIPCION</th>
        <th scope="col">ID USUARIO</th>

    </tr>
    </thead>
    <tbody>
    {% for c in cliente %}
    <tr>
        <td>{{c.id_cliente}}</td>
        <td>{{c.fecha_inicio_suscripcion}}</td>
        <td>{{c.suscripcion_activa}}</td>
        <td>{{c.fecha_pago}}</td>
        <td>{{c.detalles_adicionales}}</td>
        <td>{{c.pedidos_activos}}</td>
        <td>{{c.valor_suscripcion}}</td>
        <td>{{c.id_usuario}}</td>
        <td><a href="{% url 'clienteUpdate' c.id_cliente %}">Actualizar</a></td>
        <td><a href="{% url 'clienteDelete' c.id_cliente %}">Eliminar</a></td>

    </tr>
    {% endfor %}
    </tbody>
</table>
</body>
</html>

spa/templates/home/clienteUpdate.html
{% extends 'home/base.html' %}
{% load staticfiles %}
 {% block content %}
  {% block title %}
    <title>Login</title>
  {%endblock title%}
  <link href="{% static 'home/css/login.css' %}" rel="stylesheet" />
  <div class="login">
    <div class="row">
        <div class="col-sm-4 col-sm-offset-4 form-box">
            <div class="form-top">
                <div class="form-top-left">
                    <h2>Actualizar Perfil</h2>
                    <form class="post-form" method="POST" enctype='multipart/form-data'>
                        {% csrf_token %}

                        {% for hidden in formularioUser.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                        {{ formularioUser.as_p }}

                        {% for hidden in formularioPerfil.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                        {{ formularioPerfil.as_p }}

                        {% for hidden in formularioCliente.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                        {{ formularioCliente.as_p }}

                        <input class="btn" type="submit" value="Aceptar">
                    </form>
                </div>
            </div>
        </div>
    </div>
  </div>
 {% endblock%}

spa/templates/home/clienteUpdatePerfil.html
{% extends 'home/base.html' %}
{% load staticfiles %}
 {% block content %}
  {% block title %}
    <title>Login</title>
  {%endblock title%}
  <link href="{% static 'home/css/login.css' %}" rel="stylesheet" />
  <div class="login">
    <div class="row">
        <div class="col-sm-4 col-sm-offset-4 form-box">
            <div class="form-top">
                <div class="form-top-left">
                    <h3>Inicia sesión con</h3><br><br>

                    <a href="{% url 'social:begin' 'facebook'%}" class="btn-facebook btn-lg">
                        <i class="fa fa-facebook fa-fw"></i>
                        <span class="network-name">Facebook...</span>
                    </a>
                    <br><br>

                </div>
                <div class="socialLogin-separator">

                    <span>o</span>
                    <hr>

                </div>
                <div><p>Introduce tu usuario y contraseña para entrar:</p></div>

            </div>
            <div class="form-bottom">
                <form role="form" action="/login" method="post" class="login-form">
                  <div class="form-group">
                        <label class="sr-only" for="form-username">Username</label>
                        <input type="text" name="username" placeholder="Username..." class="form-username form-control" id="form-username">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" for="form-password">Password</label>
                        <input type="password" name="password" placeholder="Password..." class="form-password form-control" id="form-password">
                    </div>
                    <a href="#">¿Has olvidado tu contraseña?</a>
                    <br><br><br>

                   {% csrf_token %}

                    <button type="submit" class="btn">Inicia sesión</button>
                    <br><br><br>
                    <span>¿Eres nuevo en {{nombre_app}}? </span> <a href="#"> Registrate</a>
                </form>
            </div>
        </div>
    </div>
</div>
 {% endblock%}

spa/templates/home/contratoCreate.html
<!doctype html>
{% extends 'home/base.html' %} {% load staticfiles %} {% block content %} {% block title %}
Create{%endblock title%}

<link href="{% static 'home/css/restaurantes.css' %}" rel="stylesheet" />
<br><br><br><br>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
<div class="container" >
<h2>Crear Detalle contrato</h2>
<form action="#" method="POST" enctype="multipart/form-data">{% csrf_token %}
    {% for hidden in formulario.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    <label for="codigo"><small>* codigo</small></label><input type="text" name="codigo" value=""><br>
    <label for="detalles"><small>* detalles</small></label><input type="text" name="detalles" value=""><br>
    <label for="vigencia"><small>* vigencia</small></label><input type="number" name="vigencia" value=""><br>
    <label for="fecha_inicio"><small>* fecha_inicio</small></label>{{formulario.fecha_inicio}}<br>
    <label for="fecha_fin"><small>* fecha_fin</small></label>{{formulario.fecha_fin}}<br>
    <label for="valor"><small>* valor</small></label>{{formulario.valor}}<br>
    <label for="ruta_contrato"><small>* ruta_contrato</small></label>{{formulario.ruta_contrato}}<br>
    <label for="id_proveedor"><small>* id_proveedor</small></label>{{formulario.id_proveedor}}<br>
    <label for="id_sucursal"><small>* id_sucursal</small></label>{{formulario.id_sucursal}}<br>

    <input type="submit" value="submit">

</form>
</div>
{% endblock content %}
</body>
</html>

spa/templates/home/detallepedidoCreate.html
<!doctype html>
{% extends 'home/base.html' %} {% load staticfiles %} {% block content %} {% block title %}
Create{%endblock title%}

<link href="{% static 'home/css/restaurantes.css' %}" rel="stylesheet" />
<br><br><br><br>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>

<div class="container" >
<h2>Crear Detalle Pedido</h2>
<form action="#" method="POST">{% csrf_token %}
    {% for hidden in formulario.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    <label for="valor"><small>* valor</small></label><input type="text" name="valor" value=""><br>
    <label for="observaciones"><small>* observaciones</small></label><input type="text" name="observaciones" value=""><br>
    <label for="cantidad_solicitada"><small>* cantidad_solicitada</small></label><input type="text" name="cantidad_solicitada" value=""><br>
    <label for="id_pedido"><small>* id_pedido</small></label>{{formulario.id_pedido}}<br>
    <label for="id_plato"><small>* id_plato</small></label>{{formulario.id_plato}}<br>
    <label for="id_sucrusal"><small>* id_sucrusal</small></label>{{formulario.id_sucrusal}}<br>

    <input type="submit" value="submit">

</form>
 </div>
{% endblock content %}
</body>
</html>

spa/templates/home/detallepedidoUpdate.html
<!DOCTYPE html>
{% extends 'home/base.html' %} {% load staticfiles %} {% block content %} {% block title %}
Create{%endblock title%}

<link href="{% static 'home/css/restaurantes.css' %}" rel="stylesheet" />
<br><br><br><br>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div class="container" >
<h2>Actualizar PEDIDO</h2>
<form action="#" method="POST">{% csrf_token %}
    {% for hidden in formulario2.hidden_fields %}
        {{ hidden }}
    {% endfor %}

       <label for="valor"><small>* valor</small></label>{{formulario.valor}}<br>
   <label for="observaciones"><small>* observaciones</small></label>{{formulario.observaciones}}<br>
    <label for="cantidad_solicitada"><small>* cantidad_solicitada</small></label>{{formulario.cantidad_solicitada}}<br>
    <label for="id_pedido"><small>* id_pedido</small></label>{{formulario.id_pedido}}<br>
    <label for="id_plato"><small>* id_plato</small></label>{{formulario.id_plato}}<br>
    <label for="id_sucrusal"><small>* id_sucrusal</small></label>{{formulario.id_sucrusal}}<br>
    <input type="submit" value="submit">
</form>
</div>
{% endblock content %}
</body>
</html>

id_plato
id_sucrusal

spa/templates/home/horariotransportistaUpdate.html
<!doctype html>
{% extends 'home/base.html' %} {% load staticfiles %} {% block content %} {% block title %}
Create{%endblock title%}

<link href="{% static 'home/css/restaurantes.css' %}" rel="stylesheet" />
<br><br><br><br>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
<div class="container" >
<h2>Actualizar Horario Transportista</h2>
<form action="#" method="POST">{% csrf_token %}
    {% for hidden in formulario2.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    <label for="dias"><small>* dias</small></label>{{formulario.dias}}<br>
    <label for="horas"><small>* horas</small></label>{{formulario.horas}}<br>
    <label for="id_transportista"><small>* id_transportista</small></label>{{formulario.id_transportista}}<br>
    <input type="submit" value="submit">

</form>
 </div>
{% endblock content %}
</body>
</html>

spa/templates/home/personaUpdate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Actualizar Persona</h2>
<form action="#" method="POST">{% csrf_token %}
    {% for hidden in formulario.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    <label for="nombres"><small>* NOMBRES</small> {{ formulario.nombres }}</label><br>
    <label for="apellidos"><small>* APELLIDOS</small> {{ formulario.apellidos}} </label><br>
    <label for="cedula"><small>* CEDULA</small> {{ formulario.cedula}} </label><br>
    <label for="telefono"><small>* TELEFONO</small> {{ formulario.telefono}} </label><br>
    <label for="sexo"><small>* SEXO</small> {{ formulario.sexo}} </label><br>
    <label for="direccion"><small>* DIRECCION</small> {{ formulario.direccion}} </label><br>
    <label for="coordenadas"><small>* COORDENDAS</small> {{ formulario.coordenadas}} </label><br>
    <input type="submit" value="submit">


</form>
</form>
</body>
</html>

spa/templates/home/platoUpdate.html
{% extends 'home/base.html' %} {% load staticfiles %} {% block content %} {% block title %}
Create{%endblock title%}
<!--Estilos temporales-->
<style>
    label{
        width: 15%;
    }
</style>
<!---->

<link href="{% static 'home/css/restaurantes.css' %}" rel="stylesheet" />
<br><br><br>
 <div class="container">
     <h2>Actualizar Sucursal</h2>

     <form action="#" method="POST" enctype="multipart/form-data">{% csrf_token %}
    <label for="nombre_producto"><small>* nombre_producto</small></label>{{formulario.nombre_producto}}<br>
    <label for="ruta_foto"><small>* ruta_foto</small></label>{{formulario.ruta_foto}}<br>
    <label for="descripcion"><small>* descripcion</small></label>{{formulario.descripcion}}<br>
    <label for="cantidad_diaria"><small>*cantidad_diaria</small> </label>{{formulario.cantidad_diaria}}<br>
    <label for="venta_aproximada"><small>* venta_aproximada</small></label>{{formulario.venta_aproximada}}<br>
    <label for="hora_mayor_venta"><small>* hora_mayor_venta</small></label>{{formulario.hora_mayor_venta}}<br>
    <label for="cantidad_mayor_venta"><small>* cantidad_mayor_venta</small></label>{{formulario.cantidad_mayor_venta}}<br>
    <label for="existencia_actual"><small>* existencia_actual</small></label></label>{{formulario.existencia_actual}}<br>
    <label for="id_menu"><small>* id_menu</small></label>{{formulario.id_menu}}<br>
    <label for="id_platocategoria"><small>* id_platocategoria</small></label>{{formulario.id_platocategoria}}<br>

    <input type="submit" value="submit">
</form>
</div>
{% endblock content %}

spa/templates/home/redsocialUpdate.html
<!DOCTYPE html>
{% extends 'home/base.html' %} {% load staticfiles %} {% block content %} {% block title %}
Create{%endblock title%}

<link href="{% static 'home/css/restaurantes.css' %}" rel="stylesheet" />
<br><br><br><br>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container" >
<h2>Actualizar Coordenadas</h2>
<form action="#" method="POST">{% csrf_token %}
    {% for hidden in formulario2.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    <label for="nombre_red_social"><small>*nombre_red_social</small></label>{{formulario.nombre_red_social}}<br>
     <label for="cuenta_persona"><small>* cuenta_persona</small></label>{{formulario.cuenta_persona}}<br>
     <label for="id_proveedor"><small>* id_proveedor</small></label>{{formulario.id_proveedor}}<br>
    <input type="submit" value="submit">
</form>
    </div>
{% endblock content %}
</body>
</html>

spa/templates/home/sucursalCreate.html
{% extends 'home/base.html' %} {% load staticfiles %} {% block content %} {% block title %}
    Create{% endblock title %}

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular-animate.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular-route.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular-aria.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular-messages.min.js"></script>

    <script src="{% static 'home/js/OpenLayers/OpenLayers.js' %}"></script>
    <script type="text/javascript">


        var punto;
        var map, measureControls, vectorLayer;

        var mapaApp = angular.module('mapaApp', ['ngRoute']);
        mapaApp.controller('mapaCtrl', function ($scope, $route) {
            $scope.obtenerDireccion = function () {
                alert('1');
                /**ModalService.showModal({
                    templateUrl: "modal.html",
                    controller: "ModalController"
                  }).then(function(modal) {

                    //it's a bootstrap element, use 'modal' to show it
                    modal.element.modal();
                    modal.close.then(function(result) {
                      console.log(result);
                    });
                  });*/

            }
            function init() {

                texto = "PC1";
                var lon = -79.210953;
                var lat = -4.0114529;

                map = new OpenLayers.Map("map");
                var mapnik = new OpenLayers.Layer.OSM();
                punto = new OpenLayers.Layer.Vector("Puntos");
                vectorLayer = new OpenLayers.Layer.Vector("Overlay");

                var lonlatObject1 = new OpenLayers.LonLat(lon, lat).transform(
                        new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
                        new OpenLayers.Projection("EPSG:900913") // to Spherical Mercator Projection
                );
                var lonlatObject2 = new OpenLayers.LonLat(lon, lat).transform(
                        new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
                        new OpenLayers.Projection("EPSG:900913") // to Spherical Mercator Projection
                );
                /**var feature = new OpenLayers.Feature.Vector(//-79.198753246573,-3.9866758993433
                 new OpenLayers.Geometry.Point(lon, lat).transform(new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
                 new OpenLayers.Projection("EPSG:900913")),
                 {description: texto},
                 {externalGraphic: "{% static 'home/img/redMarker.png' %}", graphicHeight: 25, graphicWidth: 21, graphicXOffset: -12, graphicYOffset: -25}
                 );*/
                var punto1 = {"type": "Point", "coordinates": [lonlatObject1.lon, lonlatObject1.lat]};
                var geojson = new OpenLayers.Format.GeoJSON();
                punto.addFeatures(geojson.read(punto1));
                //punto.addFeatures(feature);
                map.addLayers([mapnik, punto, vectorLayer]);

                var controls = {
                    selector: new OpenLayers.Control.SelectFeature(vectorLayer, {
                        onSelect: function (feature) {
                            createPopup(feature);
                        }
                        , onUnselect: destroyPopup
                    })
                };

                map.addControl(controls['selector']);
                controls['selector'].activate();

                function createPopup(feature) {
                    feature.popup = new OpenLayers.Popup.FramedCloud("pop",
                            feature.geometry.getBounds().getCenterLonLat(),
                            null,
                            '<div class="markerContent">' + feature.data.description + '</div>',
                            null,
                            true,
                            function () {
                                controls['selector'].unselectAll();
                            }
                    );
                    //feature.popup.closeOnMove = true;
                    map.addPopup(feature.popup);
                }

                function destroyPopup(feature) {
                    feature.popup.destroy();
                    feature.popup = null;
                }

                map.addControl(new OpenLayers.Control.PanZoomBar());
                map.setCenter(new OpenLayers.LonLat(lon, lat) // Center of the map
                        .transform(
                                new OpenLayers.Projection("EPSG:4326"),
                                new OpenLayers.Projection("EPSG:900913")
                        ), 14
                );

                map.events.register("click", map, function (e) {
                    map.layers[1].removeAllFeatures();
                    map.layers[2].removeAllFeatures();
                    var position = map.getLonLatFromViewPortPx(e.xy);
                    //alert(position.lat + ":" + position.lon);
                    var feature = new OpenLayers.Feature.Vector(//-79.198753246573,-3.9866758993433
                            new OpenLayers.Geometry.Point(position.lon, position.lat),
                            //.transform(new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
                            //new OpenLayers.Projection("EPSG:900913")),
                            {description: texto},
                            {
                                externalGraphic: "{% static 'home/img/redMarker.png' %}",
                                graphicHeight: 25,
                                graphicWidth: 21,
                                graphicXOffset: -12,
                                graphicYOffset: -25
                            }
                    );
                    punto.addFeatures(feature);

                });
                //inicio();
                //$rootScope.reload();
                /*actualizar();
                 setInterval(function () {
                 actualizar();
                 }, 30000);*/


            }

            $scope.inicio = function () {

            }
            init();
        });
    </script>

    <!--Estilos temporales-->
    <style>
        label {
            width: 15%;
        }
    </style>
    <!---->

    <link href="{% static 'home/css/restaurantes.css' %}" rel="stylesheet"/>
    <br><br><br>
    <div class="container" ng-app="mapaApp" ng-controller="mapaCtrl">
        <h2>Crear Sucursal</h2>

        <form action="#" method="POST" enctype="multipart/form-data">{% csrf_token %}
            {% for hidden in formulario.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            <label for="nombre_sucursal">
                <small>* nombre_sucursal</small>
            </label><input type="text" name="nombre_sucursal" value=""><br>
            <label for="razon_social">
                <small>* razon_social</small>
            </label><input name="razon_social" type="text"><br>
            <label for="telefono">
                <small>* telefono</small>
            </label><input type="text" name="telefono" value=""><br>
            <label for="telefono_contacto">
                <small>*telefono_contacto</small>
            </label><input type="text" name="telefono_contacto" value=""><br>
            <label for="dias_atencion">
                <small>* dias_atencion</small>
            </label><input type="text" name="dias_atencion" value=""><br>
            <label for="hora_atencion">
                <small>* hora_atencion</small>
            </label><input type="text" name=" hora_atencion" value=""><br>
            <label for="prioridad">
                <small>* prioridad</small>
            </label><input type="text" name="prioridad" value=""><br>
            <label for="activo">
                <small>* activo</small>
            </label>{{ formulario.activo }}<br>
            <label for="hora_pico">
                <small>* hora_pico</small>
            </label></label><input type="text" name="hora_pico" value=""><br>
            <label for="me_gusta">
                <small>* me_gusta</small>
            </label><input type="text" name="me_gusta" value=""><br>
            <label for="id_ciudad">
                <small>* id_ciudad</small>
            </label>{{ formulario.id_ciudad }}<br>
            <label for="id_direccion">
                <small>* id_direccion</small>
            </label>{{ formulario.id_direccion }}<br>
            <label for="id_proveedor">
                <small>* id_proveedor</small>
            </label>{{ formulario.id_proveedor }}<br>
            <label for="id_menu">
                <small>* id_menu</small>
            </label>{{ formulario.id_menu }}<br>
            <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                Obtener Direccion
            </button>
            <input type="submit" value="submit">
        </form>

        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Ubicacion GPS</h4>
                    </div>
                    <div ng-init="inicio()" class="modal-body">
                        <div id="map" style="width:550px; height: 550px; border: 2px solid red;"></div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <button type="button" ng-click="obtenerDireccion()" class="btn btn-primary">Aceptar</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
{% endblock content %}

spa/templates/home/transportistaRead.html
<!DOCTYPE html>
{% extends 'home/base.html' %} {% load staticfiles %} {% block content %} {% block title %}
Create{%endblock title%}

<link href="{% static 'home/css/restaurantes.css' %}" rel="stylesheet" />
<br><br><br><br>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container" >
<h2>CRUD transportista</h2>
<a  href="transportistaCreate">Crear transportista</a>
<table border="1">

    <thead>
    <tr>
        <th scope="col">id_transportista</th>
        <th scope="col">tipo_transporte</th>
        <th scope="col">tipo_servicio</th>
        <th scope="col">id_perfil</th>
    </tr>
    </thead>
    <tbody>
    {% for i in transportista %}
    <tr>
        <td>{{i.id_transportista}}</td>
        <td>{{i.tipo_transporte}}</td>
        <td>{{i.tipo_servicio}}</td>
        <td>{{i.id_perfil}}</td>
        <td><a href="{% url 'transportistaUpdate' i.id_transportista %}">Actualizar</a></td>
        <td><a href="{% url 'transportistaDelete' i.id_transportista %}">Eliminar</a></td>

    </tr>
    {% endfor %}
    </tbody>
    </div>
{% endblock content %}
</body>
</html>

spa/templates/home/usuarioRead.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>CRUD Usuario</h2>
<a  href="usuarioCreate">Crear Usuario</a>
<table border="1">

    <caption>Registro de Usuarios</caption>
    <thead>
    <tr>
        <th scope="col">Celular</th>
        <th scope="col">Nick</th>
        <th scope="col">Password</th>
        <th scope="col">Activo</th>
        <th scope="col">Foto</th>
        <th scope="col">Id Persona</th>
        <th scope="col">Id Tipo Usuario/th>
    </tr>
    </thead>
    <tbody>
    {% for p in usuarios %}


    <tr>
        <td>{{p.celular}}</td>
        <td>{{p.nick}}</td>
        <td>{{p.password}}</td>
        <td>{{p.activo}}</td>
        <td>{{p.foto}}</td>
        <td>{{p.id_persona}}</td>
        <td>{{p.id_tipo_usuario}}</td>
        <td><a href="{% url 'usuarioUpdate' p.id_usuario %}">Actualizar</a></td>
        <td><a href="{% url 'usuarioDelete' p.id_usuario %}">Eliminar</a></td>

    </tr>
    {% endfor %}
    </tbody>
</body>
</html>