spa/spa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import password_reset_confirm, password_reset_complete, password_reset_done
from spaapp.views import ResetPasswordRequestView
#from spa.spaapp import urls as surls

urlpatterns = [
    url(r'^spadmin/', include(admin.site.urls)),
    url(r'', include('spaapp.urls')),
    url(r'', include('administracionAPP.urls')),
    url(r'', include('ubicacionApp.urls')),
    url(r'', include('proveedorApp.urls')),
    url(r'', include('estadisticasApp.urls')),
    url(r'', include('valoracionApp.urls')),


    url(r'^account/reset_password', ResetPasswordRequestView.as_view(), name="password_reset"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
           {'template_name': 'reset_password/password_reset_confirm.html'},
           name='password_reset_confirm'
       ),
    url(r'^reset/password_reset_done', password_reset_done,
           {'template_name': 'reset_password/password_reset_done.html'},
           name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
           {'template_name': 'reset_password/password_reset_confirm.html'},
           name='password_reset_confirm'
           ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'reset_password/password_reset_complete.html'},
           name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spa/administracionAPP/models.py
from django.db import models

# Create your models here.
class Contacto(models.Model):
    nombre_propietario = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    ciudad = models.CharField(max_length=50)
    nombre_empresa = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50)
    tipo_negocio = models.CharField(max_length=50)
    telefono = models.CharField(max_length=10, null=True, blank=True)
    correo = models.EmailField(null=True)
    

spa/administracionAPP/forms.py
from django import forms
from administracionAPP.models import Contacto
from django.contrib.auth.models import User, Group

class ContactoForm(forms.ModelForm):

    class Meta:
        model = Contacto

        fields = [
            'nombre_propietario',
            'apellidos',
            'ciudad',
            'nombre_empresa',
            'direccion',
            'tipo_negocio',
            'telefono',
        ]
        labels = {
            'nombre_propietario' : 'Nombre Propietario',
            'apellidos' : 'Apellidos',
            'ciudad' : 'Ciudad',
            'nombre_empresa' : 'Nombre Empresa',
            'direccion' : 'Direccion',
            'tipo_negocio' : 'Tipo de Negocio',
            'telefono' : 'Teléfono',
        }
        widgets = {
            'nombre_propietario' : forms.TextInput(
                attrs={'class':'form-control fields-pl', 'required':'true'}),
            'apellidos': forms.TextInput(
                attrs={'class': 'form-control fields-pl', 'required':'true'}),
            'ciudad': forms.TextInput(
                attrs={'class': 'form-control fields-pl', 'required':'true'}),
            'nombre_empresa': forms.TextInput(
                attrs={'class': 'form-control fields-pl', 'required':'true'}),
            'direccion': forms.TextInput(
                attrs={'class': 'form-control fields-pl', 'required':'true'}),
            'tipo_negocio': forms.TextInput(
                attrs={'class': 'form-control fields-pl', 'required':'true'}),
            'telefono': forms.TextInput(
                attrs={'class': 'form-control fields-pl', 'onkeypress': 'return numeros(event)', 'required':'true'}),

        }
    


DIA_CHOICES = (
    ('Lunes', 'Lunes'),
    ('Martes', 'Martes'),
    ('Miércoles', 'Miércoles'),
    ('Jueves', 'Jueves'),
    ('Viernes', 'Viernes'),
    ('Sábado', 'Sábado'),
    ('Domingo', 'Domingo'),
)



HORA_CHOICES = (
    ('00', '00'),
    ('01', '01'),
    ('02', '02'),
    ('03', '03'),
    ('04', '04'),
    ('05', '05'),
    ('06', '06'),
    ('07', '07'),
    ('08', '08'),
    ('09', '09'),
    ('10', '10'),
    ('11', '11'),
    ('12', '12'),
    ('13', '13'),
    ('14', '14'),
    ('15', '15'),
    ('16', '16'),
    ('17', '17'),
    ('18', '18'),
    ('19', '19'),
    ('20', '20'),
    ('21', '21'),
    ('22', '22'),
    ('23', '23'),

)

MINUTO_CHOICES = (
('00', '00'),
    ('01', '01'),
    ('02', '02'),
    ('03', '03'),
    ('04', '04'),
    ('05', '05'),
    ('06', '06'),
    ('07', '07'),
    ('08', '08'),
    ('09', '09'),
    ('10', '10'),
    ('11', '11'),
    ('12', '12'),
    ('13', '13'),
    ('14', '14'),
    ('15', '15'),
    ('16', '16'),
    ('17', '17'),
    ('18', '18'),
    ('19', '19'),
    ('20', '20'),
    ('21', '21'),
    ('22', '22'),
    ('23', '23'),
    ('24', '24'),
    ('25', '25'),
    ('26', '26'),
    ('27', '27'),
    ('28', '28'),
    ('29', '29'),
    ('30', '30'),
    ('31', '31'),
    ('32', '32'),
    ('33', '33'),
    ('34', '34'),
    ('35', '35'),
    ('36', '36'),
    ('37', '37'),
    ('38', '38'),
    ('39', '39'),
    ('40', '40'),
    ('41', '41'),
    ('42', '42'),
    ('43', '43'),
    ('44', '44'),
    ('45', '45'),
    ('46', '46'),
    ('47', '47'),
    ('48', '48'),
    ('49', '49'),
    ('50', '50'),
    ('51', '52'),
    ('52', '52'),
    ('53', '53'),
    ('54', '54'),
    ('55', '55'),
    ('56', '56'),
    ('57', '57'),
    ('58', '58'),
    ('59', '59'),
)

class NuevoProveedor(forms.Form):

    ###### Form Usuario
    username = forms.EmailField(label="Correo", required=True, widget=forms.TextInput(attrs={'class': 'form-control fields-pl',
                                                                                             'type':'email', 'placeholder': 'Correo Electrónico',
                                                                                             'name': 'username', 'required': 'true'}))
    password1 = forms.CharField(error_messages={'password_mismatch': 'Las contraseñas no coinciden'} ,label ="password",
                                required=True, widget=forms.PasswordInput(attrs={'class':'form-control fields-pl', 'name':'password',
                                                                                 'type':'password', 'required': 'true', 'min':'6'}))
    confirmPassword = forms.CharField(error_messages={'required':'Obligatorio'} ,required=True, widget=forms.PasswordInput(attrs={'class':'form-control fields-pl',
                                                                                                                                  'required': 'true'}))
    first_name = forms.CharField(required=True, max_length=50, widget=forms.TextInput(attrs={'class':'form-control fields-pl', 'required': 'true'}))
    last_name = forms.CharField(required=True, max_length=50, widget=forms.TextInput(attrs={'class':'form-control fields-pl', 'required': 'true'}))

    ##### Form Proveedor
    nombre_comercial = forms.CharField(required=True, max_length=50,widget=forms.TextInput(attrs={'class': 'form-control fields-pl', 'required': 'true'}))
    telefono = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control fields-pl',
                                                                            'required': 'true'}))
    telefono_contacto = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control fields-pl', 'required': 'true'}))
    prioridad = forms.IntegerField(required=True, widget=forms.NumberInput(attrs={'class': 'form-control fields-pl', 'required': 'true'}))
    razon_social = forms.CharField(required=True,max_length=20, widget=forms.TextInput(attrs={'class': 'form-control fields-pl', 'required': 'true'}))

    #### Form Sucursal
    nombre_sucursal = forms.CharField(required=True, max_length=50, widget=forms.TextInput(attrs={'class': 'form-control fields-pl', 'required': 'true'}))
    dias_atencion_desde = forms.ChoiceField(required=True, widget=forms.Select(attrs={'required': 'true'}), choices=DIA_CHOICES)
    dias_atencion_hasta = forms.ChoiceField(required=True, widget=forms.Select(attrs={'required': 'true'}),
                                            choices=DIA_CHOICES)
    hora_atencion_hora_inicio = forms.ChoiceField(required=True, widget=forms.Select(attrs={'required':'true'}), choices=HORA_CHOICES)
    hora_atencion_minuto_inicio = forms.ChoiceField(required=True, widget=forms.Select(attrs={'required':'true'}), choices=MINUTO_CHOICES)
    hora_atencion_hora_fin = forms.ChoiceField(required=True, widget=forms.Select(attrs={'required': 'true'}),
                                                  choices=HORA_CHOICES)
    hora_atencion_minuto_fin = forms.ChoiceField(required=True, widget=forms.Select(attrs={'required': 'true'}),
                                                 choices=MINUTO_CHOICES)
    activo = forms.BooleanField(initial=True)
    hora_pico_hora = forms.ChoiceField(required=True, widget=forms.Select(attrs={'required':'true'}), choices=HORA_CHOICES)
    hora_pico_minuto = forms.ChoiceField(required=True, widget=forms.Select(attrs={'required':'true'}), choices=MINUTO_CHOICES)
    #descripcion = forms.CharField(required=True,max_length=50, widget=forms.TextInput(attrs={'class': 'form-control fields-pl', 'required': 'true'}))
    descripcion = forms.CharField(required=True, max_length=300,
                                  widget=forms.Textarea(attrs={'class': 'form-control fields-pl', 'required': 'true', 'rows': '2', 'size':'300'}))

    #### Form_Dirección
    calle_principal = forms.CharField(required=True, max_length=50, widget=forms.TextInput(attrs={'class': 'form-control fields-pl', 'required': 'true'}))
    calle_secundaria = forms.CharField(required=True, max_length=50,widget=forms.TextInput(attrs={'class': 'form-control fields-pl', 'required': 'true'}))
    numero_casa = forms.CharField(required=True, max_length=50, widget=forms.TextInput(attrs={'class': 'form-control fields-pl', 'required': 'true'}))
    referencia = forms.CharField(required=True, max_length=50, widget=forms.Textarea(attrs={'class': 'form-control fields-pl', 'required': 'true', 'rows':'2', 'size':'250'}))


    def clean(self):
        username = self.cleaned_data['username']
        password1 = self.cleaned_data['password1']
        confirmPassword = self.cleaned_data['confirmPassword']
        if User.objects.filter(username=username):
            correo_repetido = forms.ValidationError('Este correo ya existe')
            self.add_error('username', correo_repetido)

        if password1 != confirmPassword:
            pass_error = forms.ValidationError('Contraseñas no coinciden')
            self.add_error('confirmPassword', pass_error)

        if len(password1)<6:
            pass_error2 = forms.ValidationError('La contraseña debe ser de 6 o más caracteres')
            self.add_error('password1', pass_error2)

class NuevaSucursal(forms.Form):
    ###### Form Usuario
    username = forms.EmailField(label="Correo", required=True,
                                widget=forms.TextInput(attrs={'class': 'form-control fields-pl',
                                                              'type': 'email', 'placeholder': 'Correo Electrónico',
                                                              'name': 'username', 'required': 'true'}))
    password1 = forms.CharField(error_messages={'password_mismatch': 'Las contraseñas no coinciden'}, label="password",
                                required=True,
                                widget=forms.PasswordInput(attrs={'class': 'form-control fields-pl', 'name': 'password',
                                                                  'type': 'password', 'required': 'true', 'min': '6'}))
    confirmPassword = forms.CharField(error_messages={'required': 'Obligatorio'}, required=True,
                                      widget=forms.PasswordInput(attrs={'class': 'form-control fields-pl',

spa/templates/administracion/acerca_de.html
{% extends 'home/base.html' %}
{% load staticfiles %}

{% block content %}
    {% include 'bases/sucursal_head.html' %}
    {% block title %}
        <title>Acerca de</title>
    {%endblock title%}


    <div class="wrapper">
        <div class="sidebar" data-background-color="white" data-active-color="danger">
            <div class="sidebar-wrapper">
                <ul class="nav">

                    <li class="active">
                        <a href="#">
                            <i class="ti-panel"></i>
                            <p>Empresa</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'terminos_condiciones' %}">
                            <i class="ti-panel"></i>
                            <p>Términos y Condiciones</p>
                        </a>
                    </li>

                </ul>
            </div>
        </div>

        <div class="main-panel">
            <div class="content">
                <div class="container-fluid">
                    <div class="card">
                        <div class="container">

                            <h2>GoodAppetit</h2>

                            <h3>INFORMACIÓN DE OFICINAS</h3>
                            <p>Quo-Hub</p>
                            <p>Calle Crisantemos y Anturios 13 - 15</p>
                            <p>Telf. (07) 210-2999</p>
                            <p>Loja - Ecuador</p>

                            <h3>Equipo</h3>
                            <h5>Nodo</h5>
                            <ul>
                                <li><p>Ing. Jorge Barba</p></li>
                            </ul>
                            <h5>CIDSecure</h5>
                            <ul>
                                <li><p>Ing. Rommel Macas</p></li>
                            </ul>
                            <br><br>

                            <p>&copy; 2016-2017 GoodAppetit</p>
                            <p>versión 1.0.0 (beta)</p>

                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>

{% endblock %}

spa/templates/administracion/crear_sucursal.html
{% extends 'home/base.html' %}{% load staticfiles %}

{% block title %} <title>Nuevo Proveedor</title> {% endblock title %}

{% block jquery %}<script src="{% static 'home/js/jquery-3.0.0.min.js' %}" type="text/javascript"></script> {% endblock %}

{% block menuDesple %}

    <li role="separator" class="divider"></li>
    <li><a href="/cerrar">Cerrar Sesion</a></li>
{% endblock menuDesple %}

{% block content %}
    {% include 'bases/sucursal_head.html' %}

    <div class="wrapper">

        <div class="sidebar" data-background-color="white" data-active-color="danger">
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li>
                        <a href="{% url 'proveedor_admin' %}">
                            <i class="ti-panel"></i>
                            <p>Proveedores</p>
                        </a>
                    </li>
                    <li class="active">
                        <a><p>Nueva sucursal</p></a>
                    </li>
                    <li>
                        <a href="{% url 'seguimiento' %}">
                            <i class="ti-panel"></i>
                            <p>Administración</p>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="ti-map-alt"></i>
                            <p>Transportistas</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'sugerencias_admin' %}">
                            <i class="ti-agenda"></i>
                            <p>Sugerencias</p>
                        </a>
                    </li>

                </ul>

            </div>
        </div>

        <div class="main-panel">
            <div class="content">
                <div class="container-fluid">
                    <div class="card">
                        <div class="container">
                            <form class="post-form fields-active ng-pristine ng-valid" method="POST"
                                  onsubmit="return checkForm(this);">

                                <h2>Crear Usuario</h2>
                                <div class="container">
                                    {% csrf_token %}

                                    <div class="row">
                                        <label for="correo" class="col-sm-2 control-label">Correo electrónico</label>
                                        <div class="col-sm-8">
                                            {{ form.username }}
                                            {{ form.errors.username }}

                                        </div>
                                     </div>

                                    <div class="row">
                                        <label for="password" class="col-sm-2 control-label">Contraseña</label>
                                        <div class="col-sm-8">
                                          {{ form.password1 }}
                                            {{ form.errors.password1 }}
                                        </div>
                                    </div>

                                    <div class="row">
                                        <label for="confirmPassword" class="col-sm-2 control-label">Confirmar contraseña</label>
                                        <div class="col-sm-8">
                                          {{ form.confirmPassword }}
                                            {{ form.errors.confirmPassword }}
                                        </div>
                                    </div>
                                    <p id="error"></p>

                                    <div class="row">
                                        <label for="id_first_name" class="col-sm-2 control-label">Nombres</label>
                                        <div class="col-sm-8">
                                          {{ form.first_name }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label for="id_last_name" class="col-sm-2 control-label">Apellidos</label>
                                        <div class="col-sm-8">
                                          {{ form.last_name }}
                                        </div>
                                    </div>

                                    <h2>Crear Nueva Sucursal</h2>

                                    <div class="row">
                                        <label for="nombre_sucursal" class="col-sm-2 control-label">Nombre de sucursal</label>
                                        <div class="col-sm-8">
                                          {{ form.nombre_sucursal }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label for="dias_atencion" class="col-sm-2 control-label">Días de atención</label>
                                        <div class="col-sm-8">
                                          De: {{ form.dias_atencion_desde }} A: {{ form.dias_atencion_hasta }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label for="dias_atencion" class="col-sm-2 control-label">Teléfono</label>
                                        <div class="col-sm-8">
                                          {{ form.telefono }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label for="hora_atencion" class="col-sm-2 control-label">Hora de atención</label>
                                        <div class="col-sm-8">
                                          Inicio: {{ form.hora_atencion_hora_inicio }} : {{ form.hora_atencion_minuto_inicio }} Fin: {{ form.hora_atencion_hora_fin }} : {{ form.hora_atencion_minuto_fin }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label for="activo" class="col-sm-2 control-label">Activo</label>
                                        <div class="col-sm-8">
                                          {{ form.activo }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label for="hora_pico" class="col-sm-2 control-label">Hora pico</label>
                                        <div class="col-sm-8">
                                          {{ form.hora_pico_hora }} : {{ form.hora_pico_minuto }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label for="descripcion" class="col-sm-2 control-label">Descripción</label>
                                        <div class="col-sm-8">
                                          {{ form.descripcion }}
                                        </div>
                                    </div>

                                    <div class="row">
                                        <label for="id_ciudad" class="col-sm-2 control-label">Ciudad</label>
                                        <div class="col-sm-8">
                                          <select class="form-control fields-pl" name="ciudad">
                                             <option value="">Escoger ciudad</option>
                                              {% for ciu in ciudad %}
                                                  <option value="{{ ciu.pk }}" name="ciudad">{{ ciu.nombre }}</option>
                                              {% endfor %}
                                          </select>
                                        </div>
                                    </div>

                                    <h4>Dirección</h4>
                                    <div class="row">
                                        <label for="razon_social" class="col-sm-2 control-label">Calle principal</label>
                                        <div class="col-sm-8">
                                          {{ form.calle_principal }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label for="razon_social" class="col-sm-2 control-label">Calle secundaria</label>
                                        <div class="col-sm-8">
                                          {{ form.calle_secundaria }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label for="razon_social" class="col-sm-2 control-label">Número de casa</label>
                                        <div class="col-sm-8">
                                          {{ form.numero_casa }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <label for="razon_social" class="col-sm-2 control-label">Referencia</label>
                                        <div class="col-sm-8">
                                          {{ form.referencia }}
                                        </div>
                                    </div>

                                </div>

                                <div class="row">
                                    <div class="container"> <br><br>
                                        <button type="submit" class="btn btn-ok" style="margin-bottom: 30px">Guardar</button>
                                    </div>
                                </div>

                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>


<script>
    $(document).ready(function() {

        var pass1 = $('[name=password1]');
        var pass2 = $('[name=confirmPassword]');
        var confirmacion = "Las contraseñas si coinciden";
        var longitud = "La contraseña debe estar formada de 6 o más caracteres";
        var negacion = "No coinciden las contraseñas";
        var vacio = "La contraseña no puede estar vacía";
        //oculto por defecto el elemento span
        var span = $('<span></span>').insertAfter(pass2);
        span.hide();
        //función que comprueba las dos contraseñas
        function coincidePassword(){
        var valor1 = pass1.val();
        var valor2 = pass2.val();
        //muestro el span
        span.show().removeClass();
        //condiciones dentro de la función
        if(valor1 != valor2){
        span.text(negacion).addClass('negacion');
        }
        if(valor1.length==0 || valor1==""){
        span.text(vacio).addClass('negacion');
        }
        if(valor1.length<6){
        span.text(longitud).addClass('negacion');
        }
        if(valor1.length!=0 && valor1==valor2){
        span.text(confirmacion).removeClass("negacion").addClass('confirmacion');
        }
        }
        //ejecuto la función al soltar la tecla
        pass2.keyup(function(){
        coincidePassword();
        });
    });
</script>

{% endblock %}

spa/templates/administracion/proveedores_admin.html
{% extends 'home/base.html' %}{% load staticfiles %}

{% block menuDesple %}
    <li role="separator" class="divider"></li>
    <li><a href="/cerrarP">Cerrar Sesion</a></li>
{% endblock menuDesple  %}

{% block content %}
{% include 'bases/sucursal_head.html' %}


<div class="wrapper">
    <div class="sidebar" data-background-color="white" data-active-color="danger">
        <div class="sidebar-wrapper">
            <ul class="nav">
                <li class="active">
                    <a href="#">
                        <i class="ti-server"></i>
                        <p>Proveedores</p>
                    </a>

                </li>
                <li>
                    <a href="{% url 'seguimiento' %}">
                        <i class="ti-panel"></i>
                        <p>Administración</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'admin_transportista' %}">
                        <i class="ti-map-alt"></i>
                        <p>Transportistas</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'sugerencias_admin' %}">
                        <i class="ti-agenda"></i>
                        <p>Sugerencias</p>
                    </a>
                </li>

            </ul>

        </div>
    </div>


    <div class="main-panel">

        <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar bar1"></span>
                            <span class="icon-bar bar2"></span>
                            <span class="icon-bar bar3"></span>
                        </button>
                        <a class="navbar-brand" href="#">Panel de Administración</a>

                    </div>
                </div>
        </nav>


        <div class="content">
                <div class="container-fluid">

                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">

                    <a href="{% url 'nuevo_proveedor' %}" class="btn btn-ok dropdown-toggle">Nuevo Proveedor</a>
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th><b>N°</b></th>
                            <th><b>Proveedores</b></th>
                            <th><b>Categoría</b></th>
                            <th><b>Nueva Sucursal</b></th>
                        </tr>
                    </thead>
                        <tbody>

                        {% for a in prov %}
                            <tr>
                            <td></td>
                            <td>{{ a.nombre_comercial }}</td>
                            <td>{{ a.id_categoria }}</td>
                            <td><a href="{% url 'nueva_sucursal' a.id_proveedor %}">Agregar</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                            </div>
                        </div>
                    </div>

                </div>
        </div>
                    <br><br>

    </div>
</div>

<style>
        table
        {
            counter-reset: rowNumber;
        }

        table tr > td:first-child
        {
            counter-increment: rowNumber;
        }

        table tr td:first-child::before
        {
            content: counter(rowNumber);
            min-width: 1em;
            margin-right: 0.5em;
        }
    </style>


{% endblock %}